services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    ports: 
      - 9000:80
    volumes:
      - ./html:/usr/local/apache2/htdocs

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080